# docker-compose up -d --build
version: '3'

services:

  master:
      image: redis:4
      build:
         context: .
         dockerfile: Dockerfile
      volumes:
       - ./redis/master:/data
      restart: unless-stopped
  slave:
    image: redis:4
    build:
         context: .
         dockerfile: Dockerfile
    command: redis-server --slaveof redis-master 6379
    volumes:
     - ./redis/slave:/data
    restart: unless-stopped
    depends_on:
      - master
    links:
      - master:redis-master
  sentinel:
    image: redis:4-sentinel
    build: 
         context: . #./sentinel/
         dockerfile: Dockerfile-sentinel
    volumes:
     - ./redis/sentinel:/data
    depends_on:
      - master
    environment:
     - SENTINEL_DOWN_AFTER=5000
     - SENTINEL_FAILOVER=5000
    links:
     - master:redis-master
     - slave